# Generated by Django 6.0 on 2025-12-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_submission_points_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('story', 'Story'), ('ask', 'Ask'), ('job', 'Job')], default='story', max_length=10),
        ),
    ]
