# Generated by Django 5.0.6 on 2026-01-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_id_alter_submission_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
